#paint.net Palette File migrated to a .toml for serde
#Downloaded from Lospec.com/palette-list
#Palette Name: Jehkoba32
#Description: Working from my Jehkoba64 palette and trimming down to half as many colours (including transparency), this 32-colour selection is perfect for emulating early SNES-style graphics, with vibrant tones and smooth ramping.&nbsp; Guaranteed to satisfy that retro itch. â™¥<br>
#Colors: 32

#Black
colors = [
0x000000FF, #Black
0x00021cFF, #Blue0
0x1c284dFF, #Blue1
0x343473FF, #Blue2
0x2d5280FF, #Blue3
0x4d7a99FF, #Blue4
0x7497a6FF, #Blue5
0xa3ccd9FF, #Blue6
0xf0edd8FF, #White
0x732866FF, #Purple
0xa6216eFF, #Pink0
0xd94c87FF, #Pink1
0xd9214fFF, #Red
0xf25565FF, #Coral
0xf27961FF, #Orange
0x993649FF, #Brown0
0xb36159FF, #Brown1
0xf09c60FF, #Brown2
0xb38f24FF, #Dijon
0xb3b324FF, #Avacado
0xf7c93eFF, #Yellow
0x17735fFF, #Green0
0x119955FF, #Green1
0x67b31bFF, #Green2
0x1ba683FF, #Aqua0
0x47cca9FF, #Aqua1
0x96e3c9FF, #Aqua2
0x2469b3FF, #Cyan0
0x0b8be6FF, #Cyan1
0x0bafe6FF, #Cyan2
0xf28d85FF, #Pink2
0xf0bb90FF, #Pink3
]
